/**
 * Contains constants suitable for keys in messaging.
 */
const ACTION = {
  ENABLE_BLACKLIST_COOKIES: 'ENABLE_COOKIES',
  DISABLE_BLACKLIST_COOKIES: 'DISABLE_COOKIES',
  CHANGE_BLACKLIST_ENCRYPTION_TYPE: 'CHANGE_BLACKLIST_ENCRYPTION_TYPE',
  GET_BLACKLIST: 'GET_BLACKLIST',
  BLACKLIST_UPDATED: 'BLACKLIST_UPDATED',
  CLEAR_BLACKLIST: 'CLEAR_BLACKLIST',
  ADD_TO_BLACKLIST: 'ADD_TO_BLACKLIST',
  IMPORT_BLACKLIST: 'IMPORT_BLACKLIST',
  REMOVE_FROM_BLACKLIST: 'REMOVE_FROM_BLACKLIST',
  CHANGE_BLACKLIST_MATCHING: 'CHANGE_BLACKLIST_MATCHING',
  CHANGE_CONTEXT_MENU_CONTROLS: 'CHANGE_CONTEXT_MENU_CONTROLS'
};